services:
  db:
    image: postgres:17.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Laura123
      POSTGRES_DB: docker
    volumes:
      - ./data:/var/lib/postgresql/data :Z